theme: jekyll-theme-cayman
title: Ziyad Benomar
description: Hello ! I am a student in the third year of the engineering degree at the Ecole polytechnique, majoring in computer science and applied mathematics. 
